# Generated by Django 6.0.7 on 2026-07-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Location'
                )
            ],
            database_operations=[]
        )
    ]
