# Generated by Django 6.0.7 on 2026-07-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_location'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Location',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('x', models.FloatField()),
                        ('y', models.FloatField()),
                        ('z', models.FloatField()),
                        ('time', models.DateTimeField()),
                    ],
                    options={
                        'db_table': 'main_location',
                    },
                )
            ],
            database_operations=[]
        )
    ]
